FROM python:3.12-slim

# Copy uv binary
COPY --from=ghcr.io/astral-sh/uv:0.4.9 /uv /bin/uv

# Bytecode caching and linking
ENV UV_COMPILE_BYTECODE=1 UV_LINK_MODE=copy
ENV PYTHONPATH /app

WORKDIR /app

# Caching for faster builds
COPY pyproject.toml uv.lock /app/
RUN --mount=type=cache,target=/root/.cache/uv \
  uv sync --frozen --no-install-project --no-dev

# Copy application code (after dependencies are installed)
COPY . /app
RUN --mount=type=cache,target=/root/.cache/uv \
  uv sync --frozen --no-dev


# Set PATH (ensure this is correct for your environment)
ENV PATH="/app/.venv/bin:$PATH"

# Database migrations - crucial step!
RUN uv run alembic upgrade head

CMD ["python", "/app/main.py"]

