# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: auth.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'auth.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\x12\x04\x61uth\"\x1c\n\x0b\x41uthRequest\x12\r\n\x05token\x18\x01 \x01(\t\")\n\x0c\x41uthResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\"\x1e\n\x10\x43heckUserRequest\x12\n\n\x02id\x18\x01 \x01(\t\"#\n\x11\x43heckUserResponse\x12\x0e\n\x06\x65xists\x18\x01 \x01(\x08\x32?\n\x0b\x41uthService\x12\x30\n\x07GetUser\x12\x11.auth.AuthRequest\x1a\x12.auth.AuthResponse2P\n\x10\x43heckUserService\x12<\n\tCheckUser\x12\x16.auth.CheckUserRequest\x1a\x17.auth.CheckUserResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AUTHREQUEST']._serialized_start=20
  _globals['_AUTHREQUEST']._serialized_end=48
  _globals['_AUTHRESPONSE']._serialized_start=50
  _globals['_AUTHRESPONSE']._serialized_end=91
  _globals['_CHECKUSERREQUEST']._serialized_start=93
  _globals['_CHECKUSERREQUEST']._serialized_end=123
  _globals['_CHECKUSERRESPONSE']._serialized_start=125
  _globals['_CHECKUSERRESPONSE']._serialized_end=160
  _globals['_AUTHSERVICE']._serialized_start=162
  _globals['_AUTHSERVICE']._serialized_end=225
  _globals['_CHECKUSERSERVICE']._serialized_start=227
  _globals['_CHECKUSERSERVICE']._serialized_end=307
# @@protoc_insertion_point(module_scope)
